### ISSUE TITLE
[script-compiler] compile error with textlint-rule-prh

### ISSUE THREAD

**Issue by tkhk** [textlint/editor#88]
Upon enabling the latest version of `textlint-rule-prh` https://github.com/textlint-rule/textlint-rule-prh and  executing `textlint-script-compiler`, I get an error related to module resolution.

```
[
  {
    moduleIdentifier: 'node:os',
    moduleName: 'node:os',
    message: 'Module build failed: UnhandledSchemeError: Reading from "node:os" is not handled by plugins (Unhandled scheme).\n' +
      'Webpack supports "data:" and "file:" URIs by default.\n' +
      'You may need an additional plugin to handle "node:" URIs.\n' +
      '    at /workspace/node_modules/webpack/lib/NormalModule.js:838:25\n' +
      '    at Hook.eval [as callAsync] (eval at create (/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Object.processResource (/workspace/node_modules/webpack/lib/NormalModule.js:835:8)\n' +
      '    at processResource (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:397:2)\n' +
      '    at NormalModule._doBuild (/workspace/node_modules/webpack/lib/NormalModule.js:825:3)\n' +
      '    at NormalModule.build (/workspace/node_modules/webpack/lib/NormalModule.js:969:15)\n' +
      '    at /workspace/node_modules/webpack/lib/Compilation.js:1377:12\n' +
      '    at NormalModule.needBuild (/workspace/node_modules/webpack/lib/NormalModule.js:1257:32)',
    moduleId: 2999,
    moduleTrace: [ [Object], [Object] ],
    details: undefined,
    stack: 'ModuleBuildError: Module build failed: UnhandledSchemeError: Reading from "node:os" is not handled by plugins (Unhandled scheme).\n' +
      'Webpack supports "data:" and "file:" URIs by default.\n' +
      'You may need an additional plugin to handle "node:" URIs.\n' +
      '    at /workspace/node_modules/webpack/lib/NormalModule.js:838:25\n' +
      '    at Hook.eval [as callAsync] (eval at create (/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Object.processResource (/workspace/node_modules/webpack/lib/NormalModule.js:835:8)\n' +
      '    at processResource (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:397:2)\n' +
      '    at NormalModule._doBuild (/workspace/node_modules/webpack/lib/NormalModule.js:825:3)\n' +
      '    at NormalModule.build (/workspace/node_modules/webpack/lib/NormalModule.js:969:15)\n' +
      '    at /workspace/node_modules/webpack/lib/Compilation.js:1377:12\n' +
      '    at NormalModule.needBuild (/workspace/node_modules/webpack/lib/NormalModule.js:1257:32)\n' +
      '    at processResult (/workspace/node_modules/webpack/lib/NormalModule.js:764:19)\n' +
      '    at /workspace/node_modules/webpack/lib/NormalModule.js:866:5\n' +
      '    at /workspace/node_modules/loader-runner/lib/LoaderRunner.js:399:11\n' +
      '    at /workspace/node_modules/loader-runner/lib/LoaderRunner.js:221:19\n' +
      '    at /workspace/node_modules/webpack/lib/NormalModule.js:838:16\n' +
      '    at Hook.eval [as callAsync] (eval at create (/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Object.processResource (/workspace/node_modules/webpack/lib/NormalModule.js:835:8)\n' +
      '    at processResource (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:397:2)',
    compilerPath: undefined
  },
```

It seems that the direct cause of this issue is related to adding `node:path` and `node:os`.
https://github.com/textlint-rule/textlint-rule-prh/pull/104

Although script-compiler use `node-polyfill-webpack-plugin`, it has come to my attention that Webpack's resolve.fallback setting does not inherently support URIs with the `node:` prefix.
https://github.com/webpack/webpack/issues/14166

I’m not familiar with JavaScript and Node.js.
I wonder if there are any known solutions or workarounds to this issue.

**Comment by azu** [comment]
What's version of node.js?

**Comment by tkhk** [comment]
I forgot to include the version information.

```
$ node --version
v20.12.0
```

```
$ yarn list | grep -e script-compiler -e textlint-rule-prh
├─ @textlint/script-compiler@0.16.2
│  ├─ textlint-rule-prh@^5.3.0
│  └─ textlint-rule-prh@5.3.0
├─ textlint-rule-prh@6.0.0
```

I tried with Node.js v18, I got the same issue.

```
$ node --version
v18.20.0
```

**Comment by azu** [comment]
Thanks.
I confirmed it. Its looks like webpack and node-polyfill-webpack-plugin problem.

**Comment by azu** [comment]
Fixed in https://github.com/textlint/editor/releases/tag/v0.17.0
