### ISSUE TITLE
webextension build failed

### ISSUE THREAD

**Issue by massongit** [textlint/editor#95]
I tried to build webextension.
However, I get an error like this:

```
$ yarn install
$ yarn run build
$ cd packages/webextension
$ npm run dist chrome

> @textlint/webextension@0.17.0 dist
> webextension-toolbox build chrome


           ╔════════╗                     
╔══════════════════════════════╗
║     WEBEXTENSION-TOOLBOX     ║
╚══════════════════════════════╝
clean-webpack-plugin: /path/to/editor/packages/webextension/dist/chrome has been removed.

Compiling

● webpack █████████████████████████ compiling (0%)  
 

node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/path/to/editor/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/path/to/editor/node_modules/webpack/lib/NormalModule.js:417:16)
    at /path/to/editor/node_modules/webpack/lib/NormalModule.js:452:10
    at /path/to/editor/node_modules/webpack/lib/NormalModule.js:323:13
    at /path/to/editor/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /path/to/editor/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/path/to/editor/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/path/to/editor/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/path/to/editor/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/path/to/editor/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /path/to/editor/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /path/to/editor/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.8.1
npm ERR! Lifecycle script `dist` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @textlint/webextension@0.17.0 
npm ERR!   at location: /path/to/editor/packages/webextension 
```

**Comment by massongit** [comment]
If I add `NODE_OPTIONS="--openssl-legacy-provider"`, another error will occur like this:

```
$ NODE_OPTIONS="--openssl-legacy-provider" npm run dist chrome

> @textlint/webextension@0.17.0 dist
> webextension-toolbox build chrome


           ╔════════╗                     
╔══════════════════════════════╗
║     WEBEXTENSION-TOOLBOX     ║
╚══════════════════════════════╝
clean-webpack-plugin: /path/to/editor/packages/webextension/dist/chrome has been removed.
✔ success webpack compiled in 62ms
Time: 65ms
Built at: 11/11/2024 9:07:38 AM
                    Asset      Size  Chunks  Chunk Names
    scripts/background.js  1.29 KiB       0  scripts/background
 scripts/contentScript.js  1.29 KiB       1  scripts/contentScript
   scripts/edit-script.js  1.29 KiB       2  scripts/edit-script
scripts/install-dialog.js  1.29 KiB       3  scripts/install-dialog
    scripts/pageScript.js  1.29 KiB       4  scripts/pageScript
         scripts/popup.js  1.29 KiB       5  scripts/popup
Entrypoint scripts/background = scripts/background.js
Entrypoint scripts/contentScript = scripts/contentScript.js
Entrypoint scripts/edit-script = scripts/edit-script.js
Entrypoint scripts/install-dialog = scripts/install-dialog.js
Entrypoint scripts/pageScript = scripts/pageScript.js
Entrypoint scripts/popup = scripts/popup.js
[0] ./scripts/background.ts 392 bytes {0} [built] [failed] [1 error]
[1] ./scripts/contentScript.ts 392 bytes {1} [built] [failed] [1 error]
[2] ./scripts/edit-script.tsx 392 bytes {2} [built] [failed] [1 error]
[3] ./scripts/install-dialog.tsx 392 bytes {3} [built] [failed] [1 error]
[4] ./scripts/pageScript.ts 392 bytes {4} [built] [failed] [1 error]
[5] ./scripts/popup.tsx 392 bytes {5} [built] [failed] [1 error]

ERROR in ./scripts/contentScript.ts
Module build failed (from /path/to/editor/node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/path/to/editor/node_modules/ts-loader/dist/index.js:112:41)
    at Object.loader (/path/to/editor/node_modules/ts-loader/dist/index.js:15:21)

ERROR in ./scripts/edit-script.tsx
Module build failed (from /path/to/editor/node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/path/to/editor/node_modules/ts-loader/dist/index.js:112:41)
    at Object.loader (/path/to/editor/node_modules/ts-loader/dist/index.js:15:21)

ERROR in ./scripts/install-dialog.tsx
Module build failed (from /path/to/editor/node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/path/to/editor/node_modules/ts-loader/dist/index.js:112:41)
    at Object.loader (/path/to/editor/node_modules/ts-loader/dist/index.js:15:21)

ERROR in ./scripts/popup.tsx
Module build failed (from /path/to/editor/node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/path/to/editor/node_modules/ts-loader/dist/index.js:112:41)
    at Object.loader (/path/to/editor/node_modules/ts-loader/dist/index.js:15:21)

ERROR in ./scripts/background.ts
Module build failed (from /path/to/editor/node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/path/to/editor/node_modules/ts-loader/dist/index.js:112:41)
    at Object.loader (/path/to/editor/node_modules/ts-loader/dist/index.js:15:21)

ERROR in ./scripts/pageScript.ts
Module build failed (from /path/to/editor/node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/path/to/editor/node_modules/ts-loader/dist/index.js:112:41)
    at Object.loader (/path/to/editor/node_modules/ts-loader/dist/index.js:15:21)
```

**Comment by healthitJP** [comment]
Here's a response you can use as an answer to an issue related to this problem:

---

**Issue: ERR_OSSL_EVP_UNSUPPORTED in Node.js with WebPack**

If you're encountering the `ERR_OSSL_EVP_UNSUPPORTED` error when using Node.js with WebPack, it's likely due to changes introduced in Node.js v17 and later. These versions use OpenSSL 3.0, which deprecates certain legacy encryption algorithms that WebPack or related dependencies may rely on.

To resolve this issue, you can downgrade your Node.js version to v16, which does not exhibit this problem.

### Steps to Downgrade Node.js:

1. **Install NVM (Node Version Manager):**
   If you don't already have NVM installed, follow the instructions [[here](https://github.com/nvm-sh/nvm#installing-and-updating)](https://github.com/nvm-sh/nvm#installing-and-updating) to install it.

2. **Install Node.js v16:**
   Use the following command to install Node.js v16:
   ```bash
   nvm install 16
   ```

3. **Use Node.js v16:**
   Switch to Node.js v16 using:
   ```bash
   nvm use 16
   ```

4. **Verify Node.js Version:**
   Ensure you're using the correct version:
   ```bash
   node -v
   ```
   The output should be `v16.x.x`.

5. **Retry Your Command:**
   Run your WebPack-related script again:
   ```bash
   yarn dev chrome
   ```

This should resolve the issue. For a long-term solution, consider upgrading your dependencies (e.g., WebPack and its plugins) to versions compatible with Node.js v17+ and OpenSSL 3.0.

**Comment by massongit** [comment]
https://github.com/massongit/editor/actions/runs/11963789432/job/33354898918?pr=33 ( https://github.com/massongit/editor/pull/33 )

In https://github.com/textlint/editor/releases/tag/v0.12.6, I can build using Node.js 16.

**Comment by massongit** [comment]
https://github.com/massongit/editor/actions/runs/11964721420/job/33357518315?pr=35#step:6:43 ( https://github.com/massongit/editor/pull/35 )

In https://github.com/textlint/editor/releases/tag/v0.13.0, I can't it.

**Comment by azu** [comment]
https://github.com/webextension-toolbox/webextension-toolbox
I don't have strong motivation for webextension-toolbox, so you can use other methods if you don't have any problem with other methods.
Since it is unknown whether the current creation (installing userScript externally) will be compatible with Manifest V3, it is possible that the extension itself will need to be reworked.
